config/routes.rb
Osem::Application.routes.draw do

  constraints DomainConstraint do
    get '/', to: 'conferences#show'
  end

  if ENV['OSEM_ICHAIN_ENABLED'] == 'true'
    devise_for :users, controllers: { registrations: :registrations }
  else
    devise_for :users,
               controllers: {
                   registrations: :registrations, confirmations: :confirmations,
                   omniauth_callbacks: 'users/omniauth_callbacks' },
               path: 'accounts'
  end

  # Use letter_opener_web to open mails in browser (e.g. necessary for Vagrant)
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, except: [:new, :index, :create, :destroy] do
    resources :openids, only: :destroy
  end

  namespace :admin do
    resources :organizations do
      member do
        get :admins
        post :assign_org_admins
        delete :unassign_org_admins
      end
    end
    resources :users do
      member do
        patch :toggle_confirmation
      end
    end
    resource :ticket_scanning, only: [:create]
    resources :comments, only: [:index]
    resources :conferences do
      resource :contact, except: [:index, :new, :create, :show, :destroy]
      resources :schedules, except: [:edit, :update]
      resources :event_schedules, only: [:create, :update, :destroy]
      get 'commercials/render_commercial' => 'commercials#render_commercial'
      resources :commercials, only: [:index, :create, :update, :destroy]
      get '/volunteers_list' => 'volunteers#show'
      get '/volunteers' => 'volunteers#index', as: 'volunteers_info'
      patch '/volunteers' => 'volunteers#update', as: 'volunteers_update'

      resources :booths do
        member do
          patch :accept
          patch :restart
          patch :to_accept
          patch :reject
          patch :reset
          patch :to_reject
          patch :cancel
          patch :confirm
        end
      end

      resources :registrations, except: [:create, :new] do
        member do
          patch :toggle_attendance

        end
      end

      # Singletons
      resource :splashpage
      resource :venue do
        get 'venue_commercial/render_commercial' => 'venue_commercials#render_commercial'
        resource :venue_commercial, only: [:create, :update, :destroy]
        resources :rooms, except: [:show]
      end
      resource :registration_period
      resource :program do
        resources :cfps
        resources :tracks do
          member do
            patch :toggle_cfp_inclusion
            patch :restart
            patch :to_accept
            patch :accept
            patch :confirm
            patch :to_reject
            patch :reject
            patch :cancel
            patch :update_selected_schedule
          end
          resources :roles, only: [:show, :edit, :update] do
            member do
              post :toggle_user
            end
          end
        end
        resources :event_types
        resources :difficulty_levels
        post 'mass_upload_commercials' => 'commercials#mass_upload'
        resources :events do
          member do
            patch :toggle_attendance
            get :registrations
            post :comment
            patch :accept
            patch :confirm
            patch :cancel
            patch :reject
            patch :unconfirm
            patch :restart
            get :vote
          end
        end
        resources :reports, only: :index
      end

      resources :resources
      resources :tickets
      resources :sponsors, except: [:show]
      resources :lodgings, except: [:show]
      resources :targets, except: [:show]
      resources :campaigns, except: [:show]
      resources :emails, only: [:show, :update, :index]
      resources :physical_tickets, only: [:index]
      resources :roles, except: [:new, :create] do
        member do
          post :toggle_user
        end
      end

      resources :sponsorship_levels, except: [:show] do
        member do
          patch :up
          patch :down
        end
      end

      resources :questions do
        collection do
          patch :update_conference
        end
      end

      get '/revision_history' => 'versions#index'
    end

    get '/revision_history' => 'versions#index'
    get '/revision_history/:id/revert_object' => 'versions#revert_object', as: 'revision_history_revert_object'
    get '/revision_history/:id/revert_attribute' => 'versions#revert_attribute', as: 'revision_history_revert_attribute'
  end
  resources :organizations, only: [:index] do
    member do
      get :conferences
    end
  end
  resources :conferences, only: [:index, :show] do
    resources :booths do
      member do
        patch :withdraw
        patch :confirm
        patch :restart
      end
    end
    resource :program, only: [] do
      resources :proposals, except: :destroy do
        get 'commercials/render_commercial' => 'commercials#render_commercial'
        resources :commercials, only: [:create, :update, :destroy]
        member do
          get :registrations
          patch '/withdraw' => 'proposals#withdraw'
          patch '/confirm' => 'proposals#confirm'
          patch '/restart' => 'proposals#restart'
        end
      end
      resources :tracks, except: :destroy do
        member do
          patch :restart
          patch :confirm
          patch :withdraw
        end
      end
    end

    # TODO: change conference_registrations to singular resource
    resource :conference_registration, path: 'register'
    resources :tickets, only: [:index]
    resources :ticket_purchases, only: [:create, :destroy, :index]
    resources :payments, only: [:index, :new, :create]
    resources :physical_tickets, only: [:index, :show]
    resource :subscriptions, only: [:create, :destroy]
    resource :schedule, only: [:show] do
      member do
        get :events
      end
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, only: [ :index, :show ] do
        resources :rooms, only: :index
        resources :tracks, only: :index
        resources :speakers, only: :index
        resources :events, only: :index
      end
      resources :rooms, only: :index
      resources :tracks, only: :index
      resources :speakers, only: :index
      resources :events, only: :index
    end
  end

  get '/admin' => redirect('/admin/conferences')

  root to: 'conferences#index', via: [:get, :options]
end

app/models/ahoy/event.rb
module Ahoy
  class Event < ApplicationRecord
    self.table_name = 'ahoy_events'

    belongs_to :visit
    belongs_to :user

    serialize :properties, JSON
  end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < Admin::BaseController
    load_and_authorize_resource :conference, find_by: :short_title
    load_and_authorize_resource :program, through: :conference, singleton: true
    load_and_authorize_resource :event, through: :program
    load_and_authorize_resource :events_registration, only: :toggle_attendance
    # For some reason this doesn't work, so a workaround is used
    # load_and_authorize_resource :track, through: :program, only: [:index, :show, :edit]

    before_action :get_tracks, only: [:index, :show, :edit]

    # FIXME: The timezome should only be applied on output, otherwise
    # you get lost in timezone conversions...
    # around_filter :set_timezone_for_this_request

    def set_timezone_for_this_request(&block)
      Time.use_zone(@conference.timezone, &block)
    end

    def index
      @difficulty_levels = @program.difficulty_levels
      @event_types = @program.event_types
      @tracks_distribution_confirmed = @conference.tracks_distribution(:confirmed)
      @event_distribution = @conference.event_distribution
      @scheduled_event_distribution = @conference.scheduled_event_distribution
      @file_name = "events_for_#{@conference.short_title}"
      @event_export_option = params[:event_export_option]

      respond_to do |format|
        format.html
        # Explicity call #to_json to avoid the use of EventSerializer
        format.json { render json: Event.where(state: :confirmed, program: @program).to_json }
        format.xlsx do
          response.headers['Content-Disposition'] = "attachment; filename=\"#{@file_name}.xlsx\""
          render 'events'
        end
        format.pdf {render 'events'}
        format.csv do
          response.headers['Content-Disposition'] = "attachment; filename=\"#{@file_name}.csv\""
          render 'events'
        end
      end
    end

    def show
      @event_types = @program.event_types
      @comments = @event.root_comments
      @comment_count = @event.comment_threads.count
      @ratings = @event.votes.includes(:user)
      @difficulty_levels = @program.difficulty_levels
      @versions = @event.versions |
       PaperTrail::Version.where(item_type: 'Commercial').where('object LIKE ?', "%commercialable_id: #{@event.id}\ncommercialable_type: Event%") |
       PaperTrail::Version.where(item_type: 'Commercial').where('object_changes LIKE ?', "%commercialable_id:\n- \n- #{@event.id}\ncommercialable_type:\n- \n- Event%") |
       PaperTrail::Version.where(item_type: 'Vote').where('object_changes LIKE ?', "%\nevent_id:\n- \n- #{@event.id}\n%") |
       PaperTrail::Version.where(item_type: 'Vote').where('object LIKE ?', "%\nevent_id: #{@event.id}\n%")
    end

    def edit
      @event_types = @program.event_types
      @comments = @event.root_comments
      @comment_count = @event.comment_threads.count
      @user = @event.submitter
      @url = admin_conference_program_event_path(@conference.short_title, @event)
      @languages = @program.languages_list
    end

    def comment
      comment = Comment.new(comment_params)
      comment.commentable = @event
      comment.user_id = current_user.id
      comment.save!
      unless params[:parent].nil?
        comment.move_to_child_of(params[:parent])
      end

      redirect_to admin_conference_program_event_path(@conference.short_title, @event)
    end

    def update
      @languages = @program.languages_list
      if @event.update_attributes(event_params)

        if request.xhr?
          render js: 'index'
        else
          flash[:notice] = "Successfully updated event with ID #{@event.id}."
          redirect_back_or_to(admin_conference_program_event_path(@conference.short_title, @event))
        end
      else
        @url = admin_conference_program_event_path(@conference.short_title, @event)
        flash.now[:error] = 'Update not successful. ' + @event.errors.full_messages.to_sentence
        render :edit
      end
    end

    def create
      @url = admin_conference_program_events_path(@conference.short_title, @event)
      @languages = @program.languages_list
      @event.submitter = current_user

      if @event.save
        ahoy.track 'Event submission', title: 'New submission'
        redirect_to admin_conference_program_events_path(@conference.short_title), notice: 'Event was successfully submitted.'
      else
        flash.now[:error] = "Could not submit proposal: #{@event.errors.full_messages.join(', ')}"
        render action: 'new'
      end
    end

    def new
      @url = admin_conference_program_events_path(@conference.short_title, @event)
      @languages = @program.languages_list
    end

    def accept
      send_mail = @event.program.conference.email_settings.send_on_accepted
      subject = @event.program.conference.email_settings.accepted_subject.blank?
      update_state(:accept, 'Event accepted!', true, subject, send_mail)
    end

    def confirm
      update_state(:confirm, 'Event confirmed!')
    end

    def cancel
      update_state(:cancel, 'Event canceled!')
      selected_schedule = @event.program.selected_schedule
      event_schedule = EventSchedule.unscoped.where(event: @event).find_by(schedule: selected_schedule) if selected_schedule
      Rails.logger.debug "schedule: #{selected_schedule.inspect} and event_schedule #{event_schedule.inspect}"
      if selected_schedule && event_schedule
        event_schedule.enabled = false
        event_schedule.save
      else
        @event.event_schedules.destroy_all
      end
    end

    def reject
      send_mail = @event.program.conference.email_settings.send_on_rejected
      subject = @event.program.conference.email_settings.rejected_subject.blank?
      update_state(:reject, 'Event rejected!', true, subject, send_mail)
    end

    def restart
      update_state(:restart, 'Review started!')
    end

    def vote
      @ratings = @event.votes.includes(:user)

      if (votes = current_user.votes.find_by_event_id(params[:id]))
        votes.update_attributes(rating: params[:rating])
      else
        @myvote = @event.votes.build
        @myvote.user = current_user
        @myvote.rating = params[:rating]
        @myvote.save
      end

      respond_to do |format|
        format.html { redirect_to admin_conference_program_event_path(@conference.short_title, @event) }
        format.js
      end
    end

    def registrations
      @event_registrations = @event.events_registrations
    end

    def toggle_attendance
      @events_registration.attended = !@events_registration.attended

      if @events_registration.save
        head :ok
      else
        head :unprocessable_entity
      end
    end

    private

    def event_params
      params.require(:event).permit(
                                    # Set also in proposals controller
                                    :title, :subtitle, :event_type_id, :abstract, :description, :require_registration, :difficulty_level_id,
                                    # Set only in admin/events controller
                                    :track_id, :state, :language, :is_highlight, :max_attendees,
                                    # Not used anymore?
                                    :proposal_additional_speakers, :user, :users_attributes,
                                    speaker_ids: [])
    end

    def comment_params
      params.require(:comment).permit(:commentable, :body, :user_id)
    end

    def update_state(transition, notice, mail = false, subject = false, send_mail = false)
      alert = @event.update_state(transition, mail, subject, send_mail, params[:send_mail].blank?)

      if alert.blank?
        flash[:notice] = notice
        redirect_back_or_to(admin_conference_program_events_path(conference_id: @conference.short_title)) && return
      else
        flash[:error] = alert
        return redirect_back_or_to(admin_conference_program_events_path(conference_id: @conference.short_title)) && return
      end
    end

    def get_tracks
      @tracks = Track.accessible_by(current_ability).where(program: @program).confirmed
    end
  end
end

app/controllers/api/v1/events_controller.rb
module Api
  module V1
    class EventsController < Api::BaseController
      load_resource :conference, find_by: :short_title
      respond_to :json

      # Disable forgery protection for any json requests. This is required for jsonp support
      skip_before_action :verify_authenticity_token

      def index
        events = Event.includes(:track, :event_type, event_users: :user)

        if @conference
          events = events.where(program: @conference.program)
        end

        respond_with events.confirmed, callback: params[:callback]
      end
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  ##
  # Includes functions related to events
  ##
  ##
  # ====Returns
  # * +String+ -> number of registrations / max allowed registrations
  def registered_text(event)
    return "Registered: #{event.registrations.count}/#{event.max_attendees}" if event.max_attendees
    "Registered: #{event.registrations.count}"
  end

  ##
  # Checks if the voting has already started, or if it has already ended
  #
  def voting_open_or_close(program)
    return if program.voting_period?
    if program.voting_start_date > Time.current
      return 'Voting period has not started yet!'
    else # voting_end_date > Date.today because voting_start_date < voting_end_date
      return 'Voting period is over!'
    end
  end

  def replacement_event_notice(event_schedule)
    if event_schedule.present? && event_schedule.replacement?
      replaced_event = (event_schedule.intersecting_event_schedules.withdrawn.first || event_schedule.intersecting_event_schedules.canceled.first).event
      content_tag :span do
        concat content_tag :span, 'Please note that this talk replaces '
        concat link_to replaced_event.title, conference_program_proposal_path(@conference.short_title, replaced_event.id)
      end
    end
  end

  def canceled_replacement_event_label(event, event_schedule, *label_classes)
    if event.state == 'canceled' || event.state == 'withdrawn'
      content_tag :span, 'CANCELED', class: (['label', 'label-danger'] + label_classes)
    elsif event_schedule.present? && event_schedule.replacement?
      content_tag :span, 'REPLACEMENT', class: (['label', 'label-info'] + label_classes)
    end
  end

  def track_selector_input(form)
    if @program.tracks.confirmed.cfp_active.any?
      form.input :track_id, as: :select,
                            collection: @program.tracks.confirmed.cfp_active.pluck(:name, :id),
                            include_blank: '(Please select)'
    end
  end
end

app/views/admin/events/_all_with_comments.csv.haml
- headers = ['Event ID',
             'Title',
             'Abstract',
             'Start time',
             'Submitter',
             'Speaker',
             'Speaker Email',
             'Event Type',
             'Track',
             'Difficulty Level',
             'Room',
             'State',
             'Comments']
= CSV.generate_line ["Events with Comments"]
= CSV.generate_line headers
- @events.each do |event|
  - all_comments = ''
  - event.root_comments.each do |comment|
    - all_comments << "#{comment.created_at.strftime("%Y-%m-%d")} #{comment.created_at.strftime("%I:%M%p")}  #{comment.user.name}: #{comment.body}\n"
  = CSV.generate_line([event.id,
                       event.title,
                       event.abstract,
                       (event.time.present? ? "#{event.time.strftime("%Y-%m-%d")}#{event.time.strftime("%I:%M%p")} " : ''),
                       event.submitter.name,
                       event.speaker_names,
                       event.speaker_emails,
                       event.event_type.title,
                       (event.track.present? ? event.track.name : ''),
                       (event.difficulty_level.present? ? event.difficulty_level.title : ''),
                       (event.room.present? ? event.room.name : ''),
                       event.state,
                       all_comments]).html_safe

app/views/admin/events/_nested_comments.html.haml
%div{ style: "padding-left:#{padding}px" }
  .well.comment-section
    %strong= comment.user.name
    %i= comment.created_at
    %p.comment-body= comment.body
    %div
      %a.pull-right.comment-reply-link{ href: '#' } Reply
      .comment-reply
        = semantic_form_for :comment, url: comment_admin_conference_program_event_path(@conference.short_title, comment.commentable_id), method: :post do |f|
          = f.input :body
          %input{ name: 'parent', type: 'hidden', value: comment.id }
          %input{ name: 'authenticity_token', type: 'hidden', value: '#{form_authenticity_token}' }
          %button.btn.btn-primary.pull-right{ name: 'button', type: 'submit' } Add Reply
  - comment.children.each do |child|
    = render 'nested_comments', comment: child, padding: 50

app/views/admin/events/_proposal.html.haml
.row
  .col-md-12
    %h3
      = @event.title
      %br
      %small
        = @event.subtitle
      .btn-group.pull-right
        = link_to 'Registrations', registrations_admin_conference_program_event_path(@conference.short_title, @event), class: 'btn btn-success'
        = link_to 'Edit', edit_admin_conference_program_event_path(@conference.short_title, @event), class: 'btn btn-mini btn-primary'

.row
  .col-md-12
    %table.table
      %tr
        %td.col-md-2
          %b Type
        %td
          .dropdown
            = link_to '#', class: 'dropdown-toggle', id: 'type-dropdown', 'data-toggle' => 'dropdown' do
              - if @event.event_type.nil?
                Event Type
              - else
                = @event.event_type.title
              <b class='caret'></b>
            %ul.dropdown-menu
              - @event_types.each do |type|
                %li= link_to type.title,
                admin_conference_program_event_path(@conference.short_title,
                                            @event,
                                            event: { event_type_id: type.id }),
                method: :patch
      %tr
        %td
          %b Highlight
        %td
          = check_box_tag @conference.short_title, @event.id, @event.is_highlight,
            method: :patch, url: "/admin/conferences/#{@conference.short_title}/program/events/#{@event.id}?event[is_highlight]=",
            class: 'switch-checkbox', data: { size: 'small',
                                              off_color: 'warning',
                                              on_text: 'Yes',
                                              off_text: 'No' }

      %tr
        %td
          %b State
        %td
          .dropdown
            = link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do
              = @event.state.humanize
              <b class='caret'></b>
            %ul.dropdown-menu
              = render 'change_state_dropdown', event: @event
      %tr
        %td
          %b Track
        %td
          .dropdown
            = link_to '#', class: 'dropdown-toggle', id: 'track-dropdown', 'data-toggle' => 'dropdown' do
              - if @event.track.nil?
                Track
              - else
                = @event.track.name
              <b class="caret"></b>
            %ul.dropdown-menu
              - @tracks.each do |track|
                %li= link_to track.name,
                admin_conference_program_event_path(@conference.short_title,
                                            @event,
                                            event: { track_id: track.id }),
                method: :patch
      %tr
        %td
          %b Difficulty
        %td
          .dropdown
            = link_to '#', class: 'dropdown-toggle', id: 'difficulty-dropdown', 'data-toggle' => 'dropdown' do
              - if @event.difficulty_level.nil?
                Difficulty Level
              - else
                = @event.difficulty_level.title
              <b class="caret"></b>
            %ul.dropdown-menu
              - @difficulty_levels.each do |difficulty|
                %li= link_to difficulty.title, admin_conference_program_event_path(@conference.short_title,
                                            @event,
                                            event: { difficulty_level_id: difficulty.id }),
                method: :patch
      %tr
        %td
          %b Requires Registration
        %td
          = check_box_tag @conference.short_title, @event.id, @event.require_registration,
            method: :patch, url: "/admin/conferences/#{@conference.short_title}/program/events/#{@event.id}?event[require_registration]=",
            class: 'switch-checkbox', data: { size: 'small',
                                              off_color: 'warning',
                                              on_text: 'Yes',
                                              off_text: 'No' }
          - if @event.require_registration
            = registered_text(@event)

      - if @program.languages.present?
        %tr
          %td
            %b Language
          %td
            = @event.language

      - unless @event.room.nil?
        %tr
          %td
            %b Room
          %td
            = @event.room.name
      - unless @event.time.nil?
        %tr
          %td
            %b Scheduled time
          %td
            = time_with_timezone(@event.time)
      %tr
        %td
          %b Submitter
        %td
          - if @program.show_voting?
            = link_to @event.submitter.name, admin_user_path(@event.submitter)
            (
            = link_to @event.submitter.email, "mailto: #{@event.submitter.email}"
            )
          - else
            %i Hidden
      %tr
        %td
          %b Speakers
        %td
          - if @program.show_voting?
            - @event.speakers.each do |speaker|
              %div
                = link_to speaker.name, admin_user_path(speaker)
                (
                = link_to speaker.email, "mailto: #{speaker.email}"
                )
          - else
            %i Hidden
      %tr
        %td
          %b Biographies
        %td
          - @event.speakers.each do |speaker|
            - unless speaker.biography.blank?
              %b
                = speaker.name
              = markdown(speaker.biography)
      %tr
        %td
          %b Submitted on
        %td= @event.created_at
      %tr
        %td
          %b Last updated on
        %td= @event.updated_at
      %tr
        %td
          %b Abstract
        %td= markdown(@event.abstract)
      %tr
        %td
          %b Requirements
        %td= simple_format(@event.description)

      - if @conference.program && @conference.program.rating && @conference.program.rating > 0
        = render partial: 'voting'

.row
  = link_to "Comments (#{@comment_count})", '#', id: 'event-comment-link'
  #comments-div
    %hr
    %ul.media
      %div
        .row-fluid
          = semantic_form_for :comment, url: comment_admin_conference_program_event_path(@conference.short_title, @event.id), method: :post do |f|
            = f.input :body
            = f.submit 'Add Comment', class: 'btn btn-primary pull-right'
        %br
        %br
        - @comments.each do |comment|
          %div
            = render partial: 'nested_comments', locals: { comment: comment, padding: 0}

app/views/admin/events/_user_fields.html.haml
.nested-fields
  = f.inputs do
    = f.input :email
    = f.input :name
  = remove_association_link :user, f

app/views/admin/events/_voting_index.html.haml
- if @program.show_voting?
  #{event.average_rating}/#{@program.rating}
  %br
  #{pluralize(event.voters.length, 'voter')}
  %br
  - @program.rating.times do |counter|
    - if event.average_rating.to_f.round == counter + 1
      = label_tag 'label_rating', '', class: 'avgrating', avgrate: true
      = javascript_tag "$('label[avgrate=true]').prevAll().andSelf().addClass('bright');"
    - else
      = label_tag 'label_rating', '', class: 'avgrating'
  %br

- if event.voted?(current_user)
  %span.label.label-success
    Your rating: #{ event.user_rating(current_user) }
- else
  %span.label.label-danger
    Not rated

app/views/admin/events/edit.html.haml
= render 'proposals/form'

app/views/admin/events/show.html.haml
.tabbable
  %ul.nav.nav-tabs
    %li.active
      = link_to 'Proposal', '#proposal-content', 'data-toggle' => 'tab'
    %li
      = link_to 'History', '#history-content', 'data-toggle' => 'tab'
    %li
      %a{ href: '#proposal-tasks', 'data-toggle' => 'tab' }
        Tasks
        %span.label.label-danger{ style: 'border-radius: 1em;' }
          - progress_status = @event.progress_status
          = progress_status.reject{ |_key, value| value || value.nil? }.length
    %li
      = link_to 'Commercials', '#proposal-commercials', 'data-toggle' => 'tab'

  .tab-content
    #proposal-content.tab-pane.active
      = render 'proposal'
    #history-content.tab-pane
      .col-md-12
        %table.table.table-striped.table-bordered.table-hover.datatable
          %thead
            %th ID
            %th Description
            %th Actions
          %tbody
            - @versions.each do |version|
              %tr
                %td
                  = version.id
                %td
                  %p
                    = link_to_user(version.whodunnit)

                    - if version.item_type == 'Event'
                      = event_change_description(version)
                      = "event #{@event.title}"

                    - elsif version.item_type == 'Vote'
                      = vote_change_description(version)
                      = "event #{@event.title}"

                    - else
                      = general_change_description(version)
                      =  link_to 'commercial',
                                edit_admin_conference_program_event_path(conference_id: @conference.short_title,
                                        id: @event.id, anchor: 'commercials-content')

                    %small.text-muted
                      = distance_of_time_in_words(Time.now, version.created_at) + ' ago'
                      %br
                      = "(#{version.created_at.strftime('%B %-d, %Y %H:%M')})"

                  %br
                  = render partial: 'shared/object_changes', locals: { version: version }
                %td
                  = render partial: 'shared/changelog_actions', locals: { version: version }

    #proposal-tasks.tab-pane
      - progress_percentage = @event.calculate_progress
      .col-md-12
        %h3
          = @event.title
        %br
        %table.table.table-hover
          %tr
            %td= link_to "#{'Speaker'.pluralize(@event.speakers.count)} must be registered to the conference", admin_conference_registrations_path(@event.program.conference.short_title)
            %td{ 'class' => class_for_todo(progress_status['registered']) }
              %span{ 'class' => [icon_for_todo(progress_status['registered']), 'fa-lg'] }
          %tr
            %td
              - if @event.speakers.count == 1
                = link_to 'Fill out speaker\'s biography', edit_admin_user_path(@event.speakers.first)
              - else
                Fill out speaker's biography:
                = speaker_links(@event)
            %td{ 'class' => class_for_todo(progress_status['biographies']) }
              %span{ 'class' => [icon_for_todo(progress_status['biographies']), 'fa-lg'] }
          %tr
            %td= link_to 'Add a subtitle', edit_admin_conference_program_event_path(@event.program.conference.short_title, @event)
            %td{ 'class' => class_for_todo(progress_status['subtitle']) }
              %span{ 'class' => [icon_for_todo(progress_status['subtitle']), 'fa-lg'] }
          %tr
            %td= link_to 'Add a commercial', edit_admin_conference_program_event_path(@event.program.conference.short_title, @event, anchor: 'commercials-content')
            %td{ 'class' => class_for_todo(progress_status['commercials']) }
              %span{ 'class' => [icon_for_todo(progress_status['commercials']), 'fa-lg'] }
          - unless progress_status['track'].nil?
            %tr
              %td= link_to 'Add a track', edit_admin_conference_program_event_path(@event.program.conference.short_title, @event)
              %td{ 'class' => class_for_todo(progress_status['track']) }
                %span{ 'class' => [icon_for_todo(progress_status['track']), 'fa-lg'] }
          %tr
            %td= link_to 'Add a difficulty level', edit_admin_conference_program_event_path(@event.program.conference.short_title, @event)
            %td{ 'class' => class_for_todo(progress_status['difficulty_level']) }
              %span{ 'class' => [icon_for_todo(progress_status['difficulty_level']), 'fa-lg'] }
    #proposal-commercials.tab-pane
      = render partial: 'shared/media_items', locals: { commercials: @event.commercials }

app/views/admin/events/vote.js.erb
$('table#myrating').replaceWith("<%= escape_javascript(render :partial => 'voting') %>");