config/routes.rb
Osem::Application.routes.draw do

  constraints DomainConstraint do
    get '/', to: 'conferences#show'
  end

  if ENV['OSEM_ICHAIN_ENABLED'] == 'true'
    devise_for :users, controllers: { registrations: :registrations }
  else
    devise_for :users,
               controllers: {
                   registrations: :registrations, confirmations: :confirmations,
                   omniauth_callbacks: 'users/omniauth_callbacks' },
               path: 'accounts'
  end

  # Use letter_opener_web to open mails in browser (e.g. necessary for Vagrant)
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, except: [:new, :index, :create, :destroy] do
    resources :openids, only: :destroy
  end

  namespace :admin do
    resources :organizations do
      member do
        get :admins
        post :assign_org_admins
        delete :unassign_org_admins
      end
    end
    resources :users do
      member do
        patch :toggle_confirmation
      end
    end
    resource :ticket_scanning, only: [:create]
    resources :comments, only: [:index]
    resources :conferences do
      resource :contact, except: [:index, :new, :create, :show, :destroy]
      resources :schedules, except: [:edit, :update]
      resources :event_schedules, only: [:create, :update, :destroy]
      get 'commercials/render_commercial' => 'commercials#render_commercial'
      resources :commercials, only: [:index, :create, :update, :destroy]
      get '/volunteers_list' => 'volunteers#show'
      get '/volunteers' => 'volunteers#index', as: 'volunteers_info'
      patch '/volunteers' => 'volunteers#update', as: 'volunteers_update'

      resources :booths do
        member do
          patch :accept
          patch :restart
          patch :to_accept
          patch :reject
          patch :reset
          patch :to_reject
          patch :cancel
          patch :confirm
        end
      end

      resources :registrations, except: [:create, :new] do
        member do
          patch :toggle_attendance

        end
      end

      # Singletons
      resource :splashpage
      resource :venue do
        get 'venue_commercial/render_commercial' => 'venue_commercials#render_commercial'
        resource :venue_commercial, only: [:create, :update, :destroy]
        resources :rooms, except: [:show]
      end
      resource :registration_period
      resource :program do
        resources :cfps
        resources :tracks do
          member do
            patch :toggle_cfp_inclusion
            patch :restart
            patch :to_accept
            patch :accept
            patch :confirm
            patch :to_reject
            patch :reject
            patch :cancel
            patch :update_selected_schedule
          end
          resources :roles, only: [:show, :edit, :update] do
            member do
              post :toggle_user
            end
          end
        end
        resources :event_types
        resources :difficulty_levels
        post 'mass_upload_commercials' => 'commercials#mass_upload'
        resources :events do
          member do
            patch :toggle_attendance
            get :registrations
            post :comment
            patch :accept
            patch :confirm
            patch :cancel
            patch :reject
            patch :unconfirm
            patch :restart
            get :vote
          end
        end
        resources :reports, only: :index
      end

      resources :resources
      resources :tickets
      resources :sponsors, except: [:show]
      resources :lodgings, except: [:show]
      resources :targets, except: [:show]
      resources :campaigns, except: [:show]
      resources :emails, only: [:show, :update, :index]
      resources :physical_tickets, only: [:index]
      resources :roles, except: [:new, :create] do
        member do
          post :toggle_user
        end
      end

      resources :sponsorship_levels, except: [:show] do
        member do
          patch :up
          patch :down
        end
      end

      resources :questions do
        collection do
          patch :update_conference
        end
      end

      get '/revision_history' => 'versions#index'
    end

    get '/revision_history' => 'versions#index'
    get '/revision_history/:id/revert_object' => 'versions#revert_object', as: 'revision_history_revert_object'
    get '/revision_history/:id/revert_attribute' => 'versions#revert_attribute', as: 'revision_history_revert_attribute'
  end
  resources :organizations, only: [:index] do
    member do
      get :conferences
    end
  end
  resources :conferences, only: [:index, :show] do
    resources :booths do
      member do
        patch :withdraw
        patch :confirm
        patch :restart
      end
    end
    resource :program, only: [] do
      resources :proposals, except: :destroy do
        get 'commercials/render_commercial' => 'commercials#render_commercial'
        resources :commercials, only: [:create, :update, :destroy]
        member do
          get :registrations
          patch '/withdraw' => 'proposals#withdraw'
          patch '/confirm' => 'proposals#confirm'
          patch '/restart' => 'proposals#restart'
        end
      end
      resources :tracks, except: :destroy do
        member do
          patch :restart
          patch :confirm
          patch :withdraw
        end
      end
    end

    # TODO: change conference_registrations to singular resource
    resource :conference_registration, path: 'register'
    resources :tickets, only: [:index]
    resources :ticket_purchases, only: [:create, :destroy, :index]
    resources :payments, only: [:index, :new, :create]
    resources :physical_tickets, only: [:index, :show]
    resource :subscriptions, only: [:create, :destroy]
    resource :schedule, only: [:show] do
      member do
        get :events
      end
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, only: [ :index, :show ] do
        resources :rooms, only: :index
        resources :tracks, only: :index
        resources :speakers, only: :index
        resources :events, only: :index
      end
      resources :rooms, only: :index
      resources :tracks, only: :index
      resources :speakers, only: :index
      resources :events, only: :index
    end
  end

  get '/admin' => redirect('/admin/conferences')

  root to: 'conferences#index', via: [:get, :options]
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :resource, polymorphic: true
  has_many :users_roles
  has_many :users, through: :users_roles

  has_paper_trail on: [:create, :update], only: [:name, :description], meta: { conference_id: :resource_id }

  before_destroy :cancel
  scopify

  validates :name, presence: true

  validates :name, uniqueness: { scope: :resource }

  private

  # Needed to ensure that removing all user from role doesn't remove role.
  def cancel
    false
  end
end

app/controllers/admin/roles_controller.rb
module Admin
  class RolesController < Admin::BaseController
    load_and_authorize_resource :conference, find_by: :short_title
    before_action :set_selection
    authorize_resource :role, except: :index
    # Show flash message with ajax calls
    after_action :prepare_unobtrusive_flash, only: :toggle_user

    def index
      @roles = Role.where(resource: @conference)
      tracks = @conference.program.tracks.where.not(submitter: nil)
      @roles += Role.where(resource: tracks)
      authorize! :index, @role
    end

    def show
      @url = if @track
               toggle_user_admin_conference_program_track_role_path(@conference.short_title, @track, @role.name)
             else
               toggle_user_admin_conference_role_path(@conference.short_title, @role.name)
             end
      @users = @role.users
    end

    def edit
      @url = if @track
               admin_conference_program_track_role_path(@conference.short_title, @track, @role.name)
             else
               admin_conference_role_path(@conference.short_title, @role.name)
             end
      @users = @role.users
    end

    def update
      role_name = @role.name

      if @role.update_attributes(role_params)
        url = if @track
                admin_conference_program_track_role_path(@conference.short_title, @track, @role.name)
              else
                admin_conference_role_path(@conference.short_title, @role.name)
              end

        redirect_to url,
                    notice: 'Successfully updated role ' + @role.name
      else
        @role.name = role_name
        flash.now[:error] = 'Could not update role! ' + @role.errors.full_messages.to_sentence
        render :edit
      end
    end

    def toggle_user
      user = User.find_by(email: user_params[:email])
      state = user_params[:state]

      url = if @track
              admin_conference_program_track_role_path(@conference.short_title, @track, @role.name)
            else
              admin_conference_role_path(@conference.short_title, @role.name)
            end

      unless user
        redirect_to url,
                    error: 'Could not find user. Please provide a valid email!'
        return
      end

      # The conference must have at least 1 organizer
      if @role.name == 'organizer' && state == 'false' && @role.users.count == 1
        redirect_to admin_conference_role_path(@conference.short_title, @role.name),
                    error: 'The conference must have at least 1 organizer!'
        return
      end

      if @role.resource_type == 'Conference'
        role_resource = @conference
      elsif @role.resource_type == 'Track'
        role_resource = @track
      end

      # Remove user
      if state == 'false'
        if user.remove_role @role.name, role_resource
          flash[:notice] = "Successfully removed role #{@role.name} from user #{user.email}"
        else
          flash[:error] = "Could not remove role #{@role.name} from user #{user.email}"
        end
      elsif user.has_role? @role.name, role_resource
        flash[:error] = "User #{user.email} already has the role #{@role.name}"
        # Add user
      elsif user.add_role @role.name, role_resource
        flash[:notice] = "Successfully added role #{@role.name} to user #{user.email}"
      else
        flash[:error] = "Coud not add role #{@role.name} to #{user.email}"
      end

      respond_to do |format|
        format.js
        format.html { redirect_to url }
      end
    end

    protected

    def set_selection
      # Set 'organizer' as default role, when there is no other selection
      @selection = params[:id] ? params[:id].parameterize.underscore : 'organizer'

      if @selection == 'track_organizer'
        @track = @conference.program.tracks.find_by(short_name: params[:track_id])
        @role = Role.find_by(name: @selection, resource: @track)
      else
        @role = Role.find_by(name: @selection, resource: @conference)
      end
    end

    def role_params
      params.require(:role).permit(:name, :description, user_ids: [])
    end

    def user_params
      params.require(:user).permit(:email, :state)
    end
  end
end

app/views/admin/roles/_form.html.haml
.row
  .col-md-12
    .page-header
      %h2
        Role
        = @role.name.titleize
      .text-muted
        = @role.description

= semantic_form_for @role, url: @url do |f|
  .row
    .col-md-5
      = f.input :description

      = f.action :submit, as: :button, button_html: { class: 'btn btn-primary' }

app/views/admin/roles/_users.html.haml
.page-header
  %h3 Users (#{users.length})
- if users.present?
  %table.table.table-striped.table-bordered.table-hover.datatable#users
    %thead
      - if ( can? :toggle_user, @role )
        %th.col-md-1
      %th ID
      %th Name
      %th Email
    %tbody
      - users.each do |user|
        %tr
          - if ( can? :toggle_user, @role )
            %td.text-right
              = hidden_field_tag "role[user_ids][]", nil
              = check_box_tag @conference.short_title, @role.id, (@role.user_ids.include? user.id), method: :post, url: "#{@url}?user[email]=#{user.email}&user[state]=", class: 'switch-checkbox', data: { size: 'small', off_color: 'warning', on_text: 'Yes', off_text: 'No' }
          %td= user.id
          %td= user.name
          %td= user.email
- else
  %h5 No users found!

app/views/admin/roles/index.html.haml
.row
  .col-md-12.page-header
    %h2
      Roles

    .text-muted
      The available roles for the conference

  .col-md-12
    %table.table.table-bordered.table-striped.table-hover#roles
      %thead
        %th ID
        %th Name
        %th Description
        %th Users
        %th Actions
      %tbody
        - @roles.each do |role|
          %tr
            %td= role.id
            %td= role.name.titleize
            %td
              = role.description
              - if role.resource_type == 'Track'
                = link_to role.resource.name, admin_conference_program_track_path(@conference.short_title, role.resource)
            %td
              = role.users.pluck(:name).first(5).join ', '
              - if role.users.count > 5
                - if role.resource_type == 'Track'
                  = link_to '...', admin_conference_program_track_role_path(@conference.short_title, role.resource, role.name)
                - else
                  = link_to '...', admin_conference_role_path(@conference.short_title, role.name)
            %td
              .btn-group
                - if role.resource_type == 'Track'
                  = link_to 'Users', admin_conference_program_track_role_path(@conference.short_title, role.resource, role.name),
                  class: 'btn btn-success'
                  - if can? :edit, role
                    = link_to 'Edit', edit_admin_conference_program_track_role_path(@conference.short_title, role.resource, role.name),
                    class: 'btn btn-primary'
                - else
                  = link_to 'Users', admin_conference_role_path(@conference.short_title, role.name), class: 'btn btn-success'
                  - if can? :edit, role
                    = link_to 'Edit', edit_admin_conference_role_path(@conference.short_title, role.name), class: 'btn btn-primary'

app/views/admin/roles/show.html.haml
.unobtrusive-flash-container
.row
  .col-md-12
    .page-header
      %h2
        Role
        = @role.name.titleize
        - if can? :edit, @role
          - if @track
            = link_to 'Edit', edit_admin_conference_program_track_role_path(@conference.short_title, @track, @role.name),
            class: 'btn btn-primary pull-right'
          - else
            = link_to 'Edit', edit_admin_conference_role_path(@conference.short_title, @role.name), class: 'btn btn-primary pull-right'
      .text-muted
        = @role.description
        - if @track
          = link_to @track.name, admin_conference_program_track_path(@conference.short_title, @track)


.row.col-md-3
  - if ( can? :toggle_user, @role ) && !@role.new_record?

    = semantic_form_for :user, url: @url, method: :post do |u|

      = u.label 'Add user by email: '
      .input-group
        = u.input :email, label: false, placeholder: "User's email"
        .input-group-btn
          = u.submit 'Add', id: 'user-add', class: 'btn btn-primary'

.row
  .col-md-12
    #users_area
      = render partial: 'users', locals: { users: @users }

app/views/admin/roles/toggle_user.js.erb
$(".alert").remove();